[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
