[build]
  command = "bun run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"  # O la versión de Node que uses
  NEXT_PRIVATE_TARGET = "server"  # Asegura que Next.js use el modo correcto

[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
